// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketAPI.Data;

#nullable disable

namespace TicketAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319215729_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketAPI.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 3, 29, 23, 57, 28, 937, DateTimeKind.Local).AddTicks(1326),
                            EventName = "Rock Concert",
                            Price = 150.00m,
                            Type = "VIP"
                        },
                        new
                        {
                            Id = 2,
                            EventDate = new DateTime(2026, 4, 3, 23, 57, 28, 937, DateTimeKind.Local).AddTicks(1345),
                            EventName = "Theater Play",
                            Price = 45.00m,
                            Type = "Regular"
                        },
                        new
                        {
                            Id = 3,
                            EventDate = new DateTime(2026, 4, 8, 23, 57, 28, 937, DateTimeKind.Local).AddTicks(1347),
                            EventName = "Sports Game",
                            Price = 85.00m,
                            Type = "Front Row"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
